vim.keymap.set("n", "<space>p", ":Telescope find_files theme=ivy<CR>")
vim.keymap.set("n", "<space>l", ":Telescope live_grep theme=ivy<CR>")
vim.keymap.set("n", "<space>q", ":Telescope quickfix theme=ivy<CR>")
vim.keymap.set("n", "<space>b", ":Telescope buffers theme=ivy<CR>")
vim.keymap.set("n", "<space>a", ":Telescope treesitter theme=ivy<CR>")
vim.keymap.set("n", "<space>r", ":Telescope lsp_references theme=ivy<CR>")
vim.keymap.set("n", "<space>d", ":Telescope lsp_definitions theme=ivy<CR>")
vim.keymap.set("n", "<space>t", ":Telescope lsp_diagnistics theme=ivy<CR>")
vim.keymap.set("n", "<space>Q", ":Telescope quickfixhistory theme=ivy<CR>")

